version: '2'
services:
  pgk-service-inmemory:
    image: pgk-service-inmemory:1.1
    ports:
    - 9003:9000
    expose:
    - 9003
    environment:
    - REDIS_URL=127.0.0.1
    depends_on:
    - redis
  redis:
    extends:
      file: redis.yml
      service: redis