version: '2'
services:
  pgk-service-inmemory:
    image: pgk-service-inmemory:1.1
    ports:
    - 9003:9000
    expose:
    - 9003
    environment:
    - REDIS_URL=10.0.75.1
    links:
    - redis:redis
    networks:
    - network-link
  redis:
    extends:
      file: redis.yml
      service: redis
    networks:
    - network-link
networks:
  network-link:
    external: true